## Problem Definition
    -Predict if a person would buy life insurance based on his age using logistic regression.
    -About Dataset - Age: Age of a person
    -bought_insurance : whether person buys Insurance or not (0 - No, 1 - Yes)
    -predict it for Age : 58,30,20,49,53


## import required packages

In [3]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### load the data

In [4]:
df = pd.read_csv("insurance_data.csv")

In [6]:
df.head()

age  bought_insurance
0   22                 0
1   25                 0
2   47                 1
3   52                 0
4   46                 1

### EDA

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   age               27 non-null     int64
 1   bought_insurance  27 non-null     int64
dtypes: int64(2)
memory usage: 564.0 bytes


In [9]:
df.describe()

age  bought_insurance
count  27.000000         27.000000
mean   39.666667          0.518519
std    15.745573          0.509175
min    18.000000          0.000000
25%    25.000000          0.000000
50%    45.000000          1.000000
75%    54.500000          1.000000
max    62.000000          1.000000

In [10]:
df.cov()

age  bought_insurance
age               247.923077          5.871795
bought_insurance    5.871795          0.259259

In [11]:
df.corr()

age  bought_insurance
age               1.000000          0.732395
bought_insurance  0.732395          1.000000

## pre-processing

In [12]:
df['bought_insurance'].value_counts()

bought_insurance
1    14
0    13
Name: count, dtype: int64

In [ ]:
# no need for
    #deal with na values
    #label encoding
    #data balancing

In [13]:
# data spliting
from sklearn.model_selection import train_test_split
x = df.drop('bought_insurance',axis=1)
y = df['bought_insurance']
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.7, random_state=123456)


### Model training

In [14]:
# model training
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

#### model evaluation

In [15]:
y_pred = model.predict(x_test)
y_true = y_test


#### precision

In [16]:
from sklearn.metrics import precision_score
precision = precision_score(y_true, y_pred)
precision

np.float64(0.8333333333333334)

#### recall

In [18]:
from sklearn.metrics import recall_score
recall = recall_score(y_true, y_pred)
recall

np.float64(1.0)

#### f1 score

In [20]:
from sklearn.metrics import f1_score
f1 = f1_score(y_true, y_pred)
f1

np.float64(0.9090909090909091)

#### classification report 

In [22]:
from sklearn.metrics import classification_report
print(classification_report(y_true, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.75      0.86         4
           1       0.83      1.00      0.91         5

    accuracy                           0.89         9
   macro avg       0.92      0.88      0.88         9
weighted avg       0.91      0.89      0.89         9



predict it for Age : 58,30,20,49,53

In [23]:
model.predict([[58]])

C:\Users\Aaditya\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([1])

In [24]:
model.predict([[30]])

C:\Users\Aaditya\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0])

In [25]:
model.predict([[20]])

C:\Users\Aaditya\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0])

In [26]:
model.predict([[49]])

C:\Users\Aaditya\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([1])

In [27]:
model.predict([[53]])

C:\Users\Aaditya\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([1])